# Taps
tap 'homebrew/bundle'
tap 'homebrew/cask-versions'

brew 'mas' # Mac App Store manager

cask 'karabiner-elements'
cask 'keyboard-maestro'
cask 'raycast'
cask 'rectangle'

# Mac App Store
mas 'Keynote', id: 409183694
mas 'Numbers', id: 409203825
mas 'Pages', id: 409201541
mas 'Video Speed Controller', id: 1588368612

# Optional Tools
cask 'spotify'

